### ISSUE TITLE
INVALID domains from dead-hosts testing

### ISSUE THREAD

**Issue by funilrys** [xxcriticxx/.pl-host-file#2]
Hey @xxcriticxx please find [here](https://github.com/dead-hosts/.pl-host-file_git_xxcriticxx/blob/6c15c369cf0faa0af9cc9af124ffa03be837e366/output/domains/INVALID/list#L4
) the list of invalid domains that are present into your list.

Have a nice day/night.
Cheers.

**Comment by xxcriticxx** [comment]
https://github.com/xxcriticxx/.pl-host-file/commit/b7ddecebc4707ec324a370386bfde28aaa90f34b
